import Head from 'next/head'
import Image from 'next/image'
import Ever from '../components/Ever'
import { SliderItems } from '../components/SliderItems'
import Slider from '../components/Slider'
import Schemes from '../components/Schemes'
import Footer from '../components/Footer'

import Buttons from '../components/Buttons'
import {useRouter} from 'next/router'
import Forms from './forms'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>LeadingLadies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
        <Ever heading="WOMEN IN INDIA" message="Of the women, By the women, For the women" para="Women all over the world have set an example for us to stand up and make the move. They have shown time and time again that they are capable of achieving great things and making a significant impact. So, if you're a woman who is hesitant to pursue your dreams and goals, let this serve as a reminder that you are more than capable. You have the power to achieve anything. The world needs more women in leadership positions, in STEM fields, in politics, and in every other industry. Meanwhile we are here to help you achieve that." button1="Apply Now" />
        <Buttons/>
        </div>
        <Slider slides={SliderItems} />
        <Schemes/>
        <Footer/>
        
    </div>
  )
}
